development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: vinylguide_development2
  pool: 5
  username: root
  password: rootsvinyl
  socket: /tmp/mysql.sock

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: vinylguide_test2
  pool: 5
  username: root
  password: rootsvinyl
  socket: /tmp/mysql.sock

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: vinylguide_production2
  pool: 5
  username: root
  password: rootsvinyl
  socket: /tmp/mysql.sock
