production:
  solr:
    hostname: 10.180.27.250
    port: 8983
    log_level: WARNING
    min_memory: 50M
    max_memory: 512M

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    min_memory: 50M
    max_memory: 512M

test:
  solr:
    hostname: localhost
    port: 8985
    log_level: WARNING